// Generated by CoffeeScript 1.6.3
(function() {
  var FileUtils, dest, fs, http, jquery, jsdom, lines, mkdirp, origin, path, request;

  http = require('http');

  request = require('request');

  fs = require('fs');

  path = require('path');

  mkdirp = require('mkdirp');

  jsdom = require('jsdom');

  jquery = fs.readFileSync("./bower_components/jquery/jquery.min.js", "utf-8");

  dest = './dest';

  origin = 'http://localhost:8080';

  FileUtils = {
    lineBy: function(filename, encoding) {
      var str;
      encoding = encoding || 'utf8';
      str = fs.readFileSync(filename, encoding);
      return str.split(String.fromCharCode(10));
    },
    dirname: function(p) {
      if (path.extname(p) !== '') {
        p = path.dirname(p);
      }
      return p;
    },
    reqfile: function(p) {
      if (/\/$/.test(p)) {
        p = "" + p + "index.html";
      }
      return p;
    }
  };

  lines = FileUtils.lineBy('filelist.txt');

  lines.forEach(function(path, index) {
    if (path === '') {
      return;
    }
    return jsdom.env({
      url: origin + path,
      src: [jquery],
      done: function(error, window) {
        var $, destpath, str;
        $ = window.$;
        str = $('#header').html();
        destpath = "" + dest + path;
        mkdirp.sync(FileUtils.dirname(destpath));
        return fs.writeFileSync(FileUtils.reqfile(destpath), str, {
          flag: 'a'
        });
      }
    });
  });

}).call(this);
