// Generated by CoffeeScript 1.6.3
(function() {
  var Yiai, fs, http, jquery, jsdom, lines, request;

  http = require('http');

  request = require('request');

  fs = require('fs');

  jsdom = require('jsdom');

  jquery = fs.readFileSync("./bower_components/jquery/jquery.min.js", "utf-8");

  Yiai = {
    lineBy: function(filename, encoding) {
      var str;
      encoding = encoding || 'utf8';
      str = fs.readFileSync(filename, encoding);
      return str.split(String.fromCharCode(10));
    }
  };

  lines = Yiai.lineBy('filelist.txt');

  lines.forEach(function(url, index) {
    if (url === '') {
      return;
    }
    return jsdom.env({
      url: url,
      src: [jquery],
      done: function(error, window) {
        var $;
        $ = window.$;
        return console.log($('body').html());
      }
    });
  });

}).call(this);
