// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  module.exports = function(yiai) {
    var encoding_is, hasPath, header_has_class;
    header_has_class = function(cls) {
      return function(path, window, res) {
        return window.$("." + cls).size() > 0;
      };
    };
    encoding_is = function() {
      return function(path, window, res) {
        return true;
      };
    };
    hasPath = function(str) {
      return function(path) {
        return path.indexOf(str) > -1;
      };
    };
    return yiai.initConfig({
      dest: "./dest",
      origin: "http://localhost:8000",
      filelist: "filelist.txt",
      patterns: {
        patternA: {
          check: [header_has_class('headerIndex'), encoding_is('utf-8')],
          replace: {
            '#container p:eq(1)': function(str) {
              return str.replace("d", "a");
            },
            '#container p:eq(0)': function(str) {
              return "----------";
            }
          }
        },
        patternB: {
          check: [header_has_class('header'), encoding_is('utf-8')],
          replace: {
            '#container p:eq(1)': function(str) {
              return str.replace("d", "a");
            },
            '#container p:eq(0)': function(str) {
              return "----------";
            }
          }
        },
        patternC: {
          check: [hasPath("/signup"), encoding_is('utf-8')],
          replace: {
            '#container p:eq(1)': function(str) {
              return str.replace("d", "a");
            },
            '#container p:eq(0)': function(str) {
              return "----------";
            }
          }
        }
      }
    });
  };

}).call(this);
